Update deploy-prod.yml

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -220,21 +220,6 @@ jobs:
             /tmp/deploy.json
             /tmp/deploy.stderr
 
-
-      - name: Ensure resource group
-        env:
-          RG: rg-${{ env.PROJECT }}-${{ env.CLIENT }}-${{ env.ENV }}-app
-          LOCATION: ${{ env.LOCATION }}
-        run: |
-          set -e
-          if ! az group show -n "$RG" >/dev/null 2>&1; then
-            echo "RG '$RG' not found. Creating..."
-            az group create -n "$RG" -l "$LOCATION" >/dev/null
-          else
-            echo "RG '$RG' exists."
-          fi
-
-
   app-func:
     needs: iac
     runs-on: ubuntu-latest
@@ -269,6 +254,19 @@ jobs:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          
+      - name: Ensure resource group
+        env:
+          RG: rg-${{ env.PROJECT }}-${{ env.CLIENT }}-${{ env.ENV }}-app
+          LOCATION: ${{ env.LOCATION }}
+        run: |
+          set -e
+          if ! az group show -n "$RG" >/dev/null 2>&1; then
+            echo "RG '$RG' not found. Creating..."
+            az group create -n "$RG" -l "$LOCATION" >/dev/null
+          else
+            echo "RG '$RG' exists."
+          fi
 
       - name: Deploy to staging slot
         if: ${{ steps.chk.outputs.exists == 'true' }}
